import type { CharacterDefinition, EventDefinition } from '@ag/schemas';

export const demoCharacter: CharacterDefinition = {
  schemaVersion: '0.1.0',
  characterId: 'char_mio',
  identity: {
    name: 'Mio',
    age: 19,
    gender: 'female',
    genderIdentity: 'female',
    sexualOrientation: 'pansexual',
    role: '图书管理员',
    description: '安静但观察力敏锐的图书管理员。',
  },
  personality: {
    traits: { gentle: 80, observant: 85 },
    independence: 80,
    confidence: 55,
    sociability: 40,
    sensitivity: 75,
    assertiveness: 45,
    empathy: 80,
    openness: 60,
  },
  preferences: { likes: ['书', '雨'], dislikes: ['噪音'], interests: ['文学'] },
  speech: {
    style: '轻声',
    tone: '温和',
    vocabulary: ['书', '谢谢'],
    examples: ['……嗯。', '你来了。'],
  },
  psychologyDefaults: {
    dependence: 30,
    security: 55,
    loneliness: 60,
    stress: 35,
    jealousy: 15,
    selfWorth: 50,
    emotionalStability: 60,
    romanticTension: 20,
  },
  cognition: {
    memoryCapacity: 80,
    encoding: 70,
    retention: 75,
    retrieval: 65,
    forgetfulness: 30,
    grudge: 20,
    obsession: 25,
    attention: 70,
    emotionalSalience: 60,
    cognitiveLoad: 30,
  },
  relationshipDefaults: { initialType: 'stranger', metrics: { trust: 0 }, tags: [] },
  secrets: [],
  goals: [],
  boundaries: [],
  gameParameters: {},
};

export const demoEvents: EventDefinition[] = [
  {
    eventId: 'event_quiet_library',
    type: 'daily',
    rarity: 'common',
    title: '安静的图书馆',
    description: '图书馆里只有翻书声。',
    baseWeight: 10,
    conditions: {},
    cooldown: { days: 1, turns: 0 },
    allowedLocationIds: ['loc_start'],
    tags: ['library', 'quiet'],
  },
];
