import type { CharacterDefinition, ModelContext } from '@ag/schemas';

export function makeDefinition(): CharacterDefinition {
  return {
    schemaVersion: '0.1.0',
    characterId: 'char_mio',
    identity: {
      name: 'Mio',
      age: 19,
      gender: 'female',
      genderIdentity: 'female',
      sexualOrientation: 'pansexual',
      role: '图书管理员',
      description: '安静但观察力敏锐的图书管理员。',
    },
    personality: {
      traits: { gentle: 80, observant: 85 },
      independence: 80,
      confidence: 55,
      sociability: 40,
      sensitivity: 75,
      assertiveness: 45,
      empathy: 80,
      openness: 60,
    },
    preferences: { likes: ['书', '雨'], dislikes: ['噪音'], interests: ['文学'] },
    speech: {
      style: '轻声',
      tone: '温和',
      vocabulary: ['书', '谢谢'],
      examples: ['……嗯。', '你来了。'],
    },
    psychologyDefaults: {
      dependence: 30,
      security: 55,
      loneliness: 60,
      stress: 35,
      jealousy: 15,
      selfWorth: 50,
      emotionalStability: 60,
      romanticTension: 20,
    },
    cognition: {
      memoryCapacity: 80,
      encoding: 70,
      retention: 75,
      retrieval: 65,
      forgetfulness: 30,
      grudge: 20,
      obsession: 25,
      attention: 70,
      emotionalSalience: 60,
      cognitiveLoad: 30,
    },
    relationshipDefaults: { initialType: 'stranger', metrics: { trust: 0 }, tags: [] },
    secrets: [{ id: 'secret_1', content: '害怕雷声', revealCondition: 'trust >= 70' }],
    goals: [{ id: 'goal_1', description: '考取图书管理资格证', priority: 60, progress: 30 }],
    boundaries: ['不讨论家庭'],
    gameParameters: { affection_gain_rate: 1 },
  };
}

export function makeContext(): ModelContext {
  const definition = makeDefinition();
  return {
    schemaVersion: '0.1.0',
    runId: 'run_1',
    turnId: 'run_1/day_001/turn_001',
    day: 1,
    time: '09:00',
    systemRules: '你是图书管理员 Mio。',
    currentState: {
      schemaVersion: '0.1.0',
      run: {
        runId: 'run_1',
        startedAt: '2026-08-16T09:00:00Z',
        day: 1,
        turn: 0,
        time: '09:00',
        dailyProgress: 0,
        dailyProgressLimit: 12,
        currentLocationId: 'loc_library',
        status: 'active',
      },
      world: {
        day: 1,
        time: '09:00',
        weekday: 'monday',
        season: 'spring',
        weather: { type: 'rain', intensity: 30, temperature: 18, visibility: 80 },
        currentLocationId: 'loc_library',
        locations: {
          loc_library: {
            locationId: 'loc_library',
            name: '图书馆',
            type: 'library',
            tags: ['quiet'],
            accessibility: 100,
            active: true,
            currentCharacters: ['char_mio'],
          },
        },
        publicEvents: [],
        activeEvents: [],
      },
      characters: {
        char_mio: {
          characterId: 'char_mio',
          identity: definition.identity,
          personality: definition.personality,
          psychology: definition.psychologyDefaults,
          emotion: { primary: 'calm', intensity: 30, valence: 10, energy: 50 },
          cognition: definition.cognition,
          physical: { energy: 70, fatigue: 20, health: 90, hunger: 20, sleepiness: 10 },
          activity: { locationId: 'loc_library', activity: '整理书架', availability: 100 },
          status: 'active',
        },
      },
      relationships: {
        rel_1: {
          relationshipId: 'rel_1',
          sourceId: 'player',
          targetId: 'char_mio',
          type: 'acquaintance',
          affection: 30,
          trust: 40,
          intimacy: 10,
          familiarity: 35,
          attraction: 25,
          conflict: 5,
          respect: 50,
          dependency: 10,
          tags: [],
          status: 'active',
          customMetrics: {},
        },
      },
      flags: {},
      playerModel: {
        perceivedTraits: {},
        perceivedIntentions: {},
        behavioralPatterns: {},
        recentBehaviorPattern: [],
        reliability: 50,
        honesty: 50,
        caring: 50,
        confidence: 50,
        romanticInterest: 0,
        perceivedControl: 50,
      },
      memories: {
        records: {
          mem_1: {
            id: 'mem_1',
            type: 'episodic',
            content: '玩家曾在雨天帮她整理旧报刊。',
            createdAt: { day: 1, time: '09:00' },
            importance: 70,
            emotionalIntensity: 60,
            valence: 25,
            strength: 80,
            accuracy: 90,
            tags: ['rain', 'help'],
            relatedCharacters: ['char_mio'],
            sourceTurnId: 'run_1/day_001/turn_001',
            retrievalCount: 0,
          },
        },
        shortTermIds: ['mem_1'],
        longTermIds: [],
        forgottenIds: [],
        lastConsolidatedDay: 1,
      },
      meta: {
        runCount: 1,
        completedRuns: 0,
        knowledge: {},
        memories: [],
        unlocks: [],
        achievements: [],
        endingsDiscovered: [],
        permanentModifiers: {},
      },
      rng: { seed: 1, state: [1], algorithm: 'xorshift128' },
    },
    recentEvents: [],
    retrievedMemories: [],
    internalState: { emotion: 'calm' },
    generationTask: { task: 'generate_scenario', outputSchema: 'scenario.schema.json' },
    budget: {
      capacity: 80,
      systemRules: 15,
      currentState: 15,
      recentEvents: 20,
      memories: 20,
      internalState: 10,
    },
  };
}
